{{- if .Values.redis.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.pvc.size }}
  storageClassName: {{ .Values.redis.pvc.storageClassName }}

{{- end }}