{{- if and .Values.uploader.enabled .Values.uploader.env.digiusher_k8s_api_token }}
apiVersion: v1
kind: Secret
metadata:
  name: digiusher-k8s-api-token
type: Opaque
stringData:
  K8S_API_TOKEN: {{ .Values.uploader.env.digiusher_k8s_api_token | quote }}
{{- end }}