{{- if and .Values.redis.enabled .Values.global.environment.dev.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.redis.name }}

{{- end }}